name: Website Monitor

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "0 * * * *"   # every hour (adjust as needed)

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run site monitor
        run: node monitor.js
